import { Activity, User } from '../types';

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: '00000000-0000-0000-0000-000000000001',
    title: 'Halı Saha Maçı (7v7)',
    description: 'Fırat Üniversitesi halı sahasında akşam maçı. Eksik 2 kişi arıyoruz. Seviye orta-üstü.',
    category: 'sports',
    competition_level: 4,
    location: 'Fırat Üniversitesi Spor Kompleksi',
    datetime: new Date(Date.now() + 86400000).toISOString(),
    creator_id: 'user1',
    max_participants: 14,
    current_participants: 12,
    match_score: 95,
  },
  {
    id: '00000000-0000-0000-0000-000000000002',
    title: 'Valorant Ranked Gecesi',
    description: 'Platin-Elmas arası takım arkadaşları arıyoruz. Discord şart.',
    category: 'esports',
    competition_level: 5,
    location: 'Discord',
    datetime: new Date(Date.now() + 3600000 * 5).toISOString(),
    creator_id: 'user2',
    max_participants: 5,
    current_participants: 3,
    match_score: 88,
  },
  {
    id: '00000000-0000-0000-0000-000000000003',
    title: 'Catan Turnuvası',
    description: 'Kahvehanede Catan ve masa oyunları gecesi. Başlangıç seviyesine uygun.',
    category: 'board_games',
    competition_level: 2,
    location: 'Merkez Kahve',
    datetime: new Date(Date.now() + 172800000).toISOString(),
    creator_id: 'user3',
    max_participants: 4,
    current_participants: 2,
    match_score: 75,
  },
  {
    id: '00000000-0000-0000-0000-000000000004',
    title: 'Hazar Gölü Doğa Yürüyüşü',
    description: 'Hafta sonu sabah yürüyüşü. Ulaşım ortak araçlarla sağlanacak.',
    category: 'outdoor',
    competition_level: 2,
    location: 'Hazar Gölü Sahili',
    datetime: new Date(Date.now() + 259200000).toISOString(),
    creator_id: 'user4',
    max_participants: 20,
    current_participants: 8,
    match_score: 60,
  },
  {
    id: '00000000-0000-0000-0000-000000000005',
    title: '3x3 Basketbol Maçı',
    description: 'Mahalle sahasında ter atmalık basket. Herkes gelebilir.',
    category: 'sports',
    competition_level: 3,
    location: 'Kültür Park Sahası',
    datetime: new Date(Date.now() + 90000000).toISOString(),
    creator_id: 'user5',
    max_participants: 6,
    current_participants: 4,
    match_score: 82,
  },
  {
    id: '00000000-0000-0000-0000-000000000006',
    title: 'CS2 Faceit Kasma',
    description: '10 level üstü, ciddi takım arkadaşı. Win odaklıyız.',
    category: 'esports',
    competition_level: 5,
    location: 'Online',
    datetime: new Date(Date.now() + 120000000).toISOString(),
    creator_id: 'user6',
    max_participants: 5,
    current_participants: 2,
    match_score: 91,
  },
  {
    id: '00000000-0000-0000-0000-000000000007',
    title: 'D&D One-Shot Macera',
    description: 'Yeni başlayanlara açık, 3-4 saatlik kısa bir macera. Zarınızı kapıp gelin.',
    category: 'board_games',
    competition_level: 1,
    location: 'Hobbit House Cafe',
    datetime: new Date(Date.now() + 300000000).toISOString(),
    creator_id: 'user7',
    max_participants: 5,
    current_participants: 4,
    match_score: 70,
  },
  {
    id: '00000000-0000-0000-0000-000000000008',
    title: 'Akşam Paten Turu',
    description: 'Sahilde sakin bir tur. Kask ve dizlik takılması önerilir.',
    category: 'outdoor',
    competition_level: 3,
    location: 'Malatya Yolu Parkuru',
    datetime: new Date(Date.now() + 150000000).toISOString(),
    creator_id: 'user8',
    max_participants: 15,
    current_participants: 5,
    match_score: 55,
  }
];

export const MOCK_SQUADS = [
  {
    id: 's1',
    name: 'Elazığ Kartalları',
    description: 'Düzenli halı saha ve basketbol maçları organize eden grup.',
    category: 'sports',
    member_count: 24,
    level: 4,
  },
  {
    id: 's2',
    name: 'Pixel Warriors',
    description: 'FPS oyunları ve turnuvalar için kurulan profesyonel topluluk.',
    category: 'esports',
    member_count: 156,
    level: 5,
  },
  {
    id: 's3',
    name: 'Zeka Oyunları Kulübü',
    description: 'Satranç, Catan ve diğer strateji oyunları meraklıları.',
    category: 'board_games',
    member_count: 42,
    level: 3,
  },
  {
    id: 's4',
    name: 'Sahil Koşucuları',
    description: 'Her sabah Hazar Gölü kenarında koşan doğa severler.',
    category: 'outdoor',
    member_count: 12,
    level: 2,
  }
];

export const MOCK_FRIENDS: User[] = [
  {
    id: 'f1',
    name: 'Burak Yılmaz',
    email: 'burak@example.com',
    interests: ['futbol', 'basketbol', 'fitness'],
    competition_level: 4,
    attended_events: 12,
    joined_events: 15,
  },
  {
    id: 'f2',
    name: 'Ayşe Demir',
    email: 'ayse@example.com',
    interests: ['valorant', 'lol', 'cs2'],
    competition_level: 5,
    attended_events: 45,
    joined_events: 50,
  },
  {
    id: 'f3',
    name: 'Caner Özcan',
    email: 'caner@example.com',
    interests: ['satranç', 'catan', 'monopoly'],
    competition_level: 3,
    attended_events: 8,
    joined_events: 10,
  },
  {
    id: 'f4',
    name: 'Selin Aktaş',
    email: 'selin@example.com',
    interests: ['koşu', 'yoga', 'tenis'],
    competition_level: 2,
    attended_events: 22,
    joined_events: 25,
  },
  {
    id: 'f5',
    name: 'Mert Korkmaz',
    email: 'mert@example.com',
    interests: ['d&d', 'wow', 'rpg'],
    competition_level: 1,
    attended_events: 5,
    joined_events: 7,
  }
];
